name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/jarred-apps/jarred-apps-docker-repo/test-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/437002318791/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider
          service_account: test-app-service-account@jarred-apps.iam.gserviceaccount.com

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'test gcloud'
        run: gcloud run deploy --image us-central1-docker.pkg.dev/jarred-apps/jarred-apps-docker-repo/test-app:ff32d24e10b871e7af500b502ae88b562e8eabfc --region us-central1 --service-account test-app-service-account@jarred-apps.iam.gserviceaccount.com

      # - name: Build Docker image
      #   run: docker build . -t $IMAGE_NAME:$GITHUB_SHA

      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: us-central1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      # - name: Push Docker image
      #   run: docker push $IMAGE_NAME:$GITHUB_SHA

      # - name: Deploy Docker image
      #   run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME:$GITHUB_SHA --region us-central1 --service-account test-app-service-account@jarred-apps.iam.gserviceaccount.com
