name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/jarred-apps/jarred-apps-docker-repo/test-app
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          service_account: test-app-service-account@jarred-apps.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:$GITHUB_SHA

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Push Docker image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push $IMAGE_NAME:$GITHUB_SHA

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME:$GITHUB_SHA --region us-central1
