name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPOSITORY_ID }}/test-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate Cloud SDK
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:$GITHUB_SHA

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$GITHUB_SHA

      - name: Deploy Docker image
        run: |
          gcloud run deploy test-app \
            --image $IMAGE_NAME:$GITHUB_SHA \
            --region ${{ secrets.GCP_REGION }} \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }}
